# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install pytest
    - name: Test with pytest
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        pytest

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install pytest pytest-cov
    - name: Generate coverage report
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        pytest --cov=./ --cov-report=term --cov-report=json:coverage-summary.json
    - name: Verify coverage file
      run: |
        ls -lR
        if [ ! -f coverage.json ]; then
          echo "coverage.json not found!"
          exit 1
        fi
    - name: Generate coverage badges
      uses: jpb06/coverage-badges-action@latest
      with:
        branches: main
        coverage-summary-path: ./coverage-summary.json
    - name: Commit coverage badges
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "docs: update coverage badges"
        file_pattern: "badges/*.svg"
