# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install pytest
    - name: Test with pytest
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        pytest

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (test + coverage)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install pytest pytest-cov

      - name: Run tests & generate coverage data
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest --cov=./ --cov-report=term --cov-report=xml   # .coverage + XML

      - name: Ensure badges directory exists
        run: mkdir -p badges

      - name: Generate SVG badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          output: badges/coverage.svg      # → ./badges/coverage.svg
          overwrite: true

      - name: Commit updated badge
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update coverage badge"
          file_pattern: "badges/coverage.svg"
