# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install pytest
    - name: Test with pytest
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        pytest

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install pytest pytest-cov

      - name: Run tests & create .coverage data file
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest --cov=./ --cov-report=term --cov-report=xml      # xml is optional; .coverage is enough

      # 1️⃣  Generate the SVG badge where you want it
      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          output: badges/coverage.svg 
          overwrite: true

      # 2️⃣  Commit the badge that was just written/updated
      - name: Commit coverage badge
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update coverage badge"
          file_pattern: "badges/coverage.svg"
